<?php
// DO NOT CHANGE THIS FILE! It is automatically generated by Tx_Extbase_Utility_Extension::createAutoloadRegistryForExtension.
// This file was generated on 2009-08-21 22:34

$extensionClassesPath = t3lib_extMgm::extPath('wine_treatment') . 'Classes/';
return array(
	'tx_winetreatment_view_pdf' => $extensionClassesPath . 'View/Pdf.php',
	'tx_winetreatment_view_category_gvopdf' => $extensionClassesPath . 'View/Category/GvoPdf.php',
	'tx_winetreatment_view_product_algpdf' => $extensionClassesPath . 'View/Product/AlgPdf.php',
	'tx_winetreatment_view_product_sipdf' => $extensionClassesPath . 'View/Product/SiPdf.php',
	'tx_winetreatment_view_product_tipdf' => $extensionClassesPath . 'View/Product/TiPdf.php',
	'tx_winetreatment_page_standardpdf' => $extensionClassesPath . 'Page/StandardPdf.php',
	'tx_winetreatment_page_twocolumnpdf' => $extensionClassesPath . 'Page/TwoColumnPdf.php',
	'tx_winetreatment_controller_categorycontroller' => $extensionClassesPath . 'Controller/CategoryController.php',
	'tx_winetreatment_controller_productcontroller' => $extensionClassesPath . 'Controller/ProductController.php',
	'tx_winetreatment_domain_repository_categoryrepository' => $extensionClassesPath . 'Domain/Repository/CategoryRepository.php',
	'tx_winetreatment_domain_repository_productrepository' => $extensionClassesPath . 'Domain/Repository/ProductRepository.php',
	'tx_winetreatment_domain_model_category' => $extensionClassesPath . 'Domain/Model/Category.php',
	'tx_winetreatment_domain_model_function' => $extensionClassesPath . 'Domain/Model/Function.php',
	'tx_winetreatment_domain_model_product' => $extensionClassesPath . 'Domain/Model/Product.php',
	'tx_winetreatment_domain_model_specinfo' => $extensionClassesPath . 'Domain/Model/SpecInfo.php',
	'tx_winetreatment_domain_model_usage' => $extensionClassesPath . 'Domain/Model/Usage.php',
	'tx_winetreatment_domain_model_wine' => $extensionClassesPath . 'Domain/Model/Wine.php',
);
?>